{
  inputs,
  outputs,
  lib,
  pkgs,
  meta,
  modulesPath,
  config,
  ...
}:

{
  nix = {
    package = pkgs.nixVersions.latest;
    extraOptions = ''
      experimental-features = nix-command flakes
    '';
  };

  imports = [
    ./nextcloud.nix
  ];

  sops = {
    defaultSopsFile = ../../secrets/sorserver/default.yaml;
    age.sshKeyPaths = [ "/etc/ssh/ssh_host_ed25519_key" ];
    secrets = {
      wireguard_private_key = { };
      nextcloud_admin_pass = { };
    };
  };

  nixpkgs = {
    overlays = [
      outputs.overlays.additions
      outputs.overlays.unstable
      inputs.alacritty-theme.overlays.default
    ];
    config = {
      permittedInsecurePackages = [ "electron-25.9.0" ];
      allowUnfree = true;
    };
  };

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  boot.kernelParams = [
    "intel_iommu=on"
    "iommu=pt"
    "module_blacklist=nouveau"
    "tpm_tis.interrupts=0"
  ];

  networking.hostName = meta.hostname;
  networking.networkmanager.enable = true;
  networking.networkmanager.dns = "systemd-resolved";
  networking.resolvconf.enable = true;
  networking.resolvconf.useLocalResolver = true;
  networking.search = [ "joejad.lan" ];
  networking.nameservers = [
    "127.0.0.1"
  ];

  time.timeZone = "America/Chicago";

  i18n.defaultLocale = "en_US.UTF-8";
  console = {
    font = "Lat2-Terminus16";
    keyMap = "us";
  };

  systemd.tmpfiles.rules = [
    "L+ /usr/local/bin - - - - /run/current-system/sw/bin/"
  ];

  virtualisation.docker = {
    enable = true;
    storageDriver = "btrfs";
    logDriver = "json-file";
    daemon.settings.features.cdi = true;
    rootless.daemon.settings.features.cdi = true;
  };

  users.users.joejad = {
    isNormalUser = true;
    shell = pkgs.zsh;
    extraGroups = [
      "wheel"
      "docker"
    ];
    packages = with pkgs; [
      tree
    ];
    hashedPassword = "$6$lGy6iRAdcwvnkJ2X$GPvLqm5DGX/HBD9iZ.Z.UOcxkU5k3lYc/Izw8vnPWC0X.tpE4087.U1V4AGjXduJHjFu76fKXJe3pK9YgmNue1";
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDzIbh1w5EeOjFTWaQ9V5PFHf5ipVNQ33sjzpsNDNgfD jade@Jades-MacBook-Pro.local"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOciDf2c/QVPKjPVgSXYg7LSg8nwL4J7JDf8mYO4cs11 Generated By Termius"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFmO691Ujio3I1tNUGEnSnyhjl0vLCBNi3Q/u0P+UvEX joejad@joejadserver"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN6MCnmxn47X/aP9pQxNmHc2I6kkZqh5R+J4KdcJUhZI jade@mini"
    ];
  };

  security.sudo.wheelNeedsPassword = false;

  programs.zsh.enable = true;

  environment.systemPackages = with pkgs; [
    age
    cifs-utils
    fluxcd
    fzf
    gcc
    git
    gnumake
    helm
    kubectl
    lazygit
    lua
    lua-language-server
    luajitPackages.luarocks-nix
    nfs-utils
    nil
    nixfmt
    opencode
    ripgrep
    samba
    sops
    starship
    stylua
    tmux
    neovim
    zoxide
    zsh
    ethtool
    networkd-dispatcher
  ];

  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = false;
      PermitRootLogin = "no";
    };
  };

  networking.firewall.enable = false;
  system.stateVersion = "23.11";

  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver
    ];
  };

  services.tailscale.enable = true;
  services.tailscale.useRoutingFeatures = "both";
  services.tailscale.extraUpFlags = [ "--accept-dns=false" ];
  services.tailscale.extraDaemonFlags = [ "--no-resolvconf" ];
  networking.firewall.checkReversePath = "loose";
  services = {
    networkd-dispatcher = {
      enable = true;
      rules."50-tailscale" = {
        onState = [ "routable" ];
        script = ''
          ethtool -K enp5s0 rx-udp-gro-forwarding on rx-gro-list o
        '';
      };
    };
  };

  networking.wg-quick.interfaces = {
    wg0 = {
      address = [ "10.10.10.8/32" ];
      privateKeyFile = config.sops.secrets.wireguard_private_key.path;
      peers = [
        {
          publicKey = "NfwRlI/IFxEfmK6VmtemBYEUpLJ0wF07wpmdz598jGs=";
          allowedIPs = [
            "10.10.10.0/24"
            "10.47.59.0/24"
          ];
          endpoint = "";
          persistentKeepalive = 25;
        }
      ];
    };
  };

  services.nfs.server.enable = true;
  services.nfs.server.exports = ''
    /var/lib 100.94.157.2/32(rw,sync,no_root_squash,no_subtree_check)
  '';

  services.unbound = {
    enable = true;
    settings = {
      server = {
        interface = [ "0.0.0.0" ];
        access-control = [
          "127.0.0.1/32 allow"
          "192.168.86.0/24 allow"
        ];
        private-domain = [ "joejad.lan" ];
        domain-insecure = [ "joejad.lan" ];
        local-zone = "\"sorenson-fam.com.\" redirect";
        local-data = [
          "\"sorenson-fam.com. IN A 192.168.86.3\""
          "\"sorenson-fam.com. IN AAAA ::ffff:192.168.86.3\""
        ];
      };
      forward-zone = [
        {
          name = "joejad.lan.";
          forward-addr = [
            "10.10.10.1"
          ];
        }
        {
          name = ".";
          forward-tls-upstream = "yes";
          forward-addr = [
            "1.1.1.1@853#cloudflare-dns.com"
            "8.8.8.8@853#dns.google.com"
          ];
        }
      ];
    };
  };

  security.acme = {
    acceptTerms = true;
    defaults.email = "joejadjavajim@icloud.com";
    certs = {
      "sorenson-fam.com" = {
        dnsProvider = "cloudflare";
        dnsPropagationCheck = true;
        environmentFile = "/var/lib/acme/.secrets/cert.env";
        group = "nginx";
        domain = "*.sorenson-fam.com";
        extraDomainNames = [ "sorenson-fam.com" ];
      };
    };
  };

  services.nginx.enable = true;

  services.immich = {
    enable = true;
    port = 2283;
    accelerationDevices = [ "/dev/dri/renderD128" ];
  };
  users.users.immich.extraGroups = [
    "video"
    "render"
  ];

  services.nginx.virtualHosts."immich.sorenson-fam.com" = {
    useACMEHost = "sorenson-fam.com";
    forceSSL = true;
    locations."/" = {
      proxyPass = "http://[::1]:${toString config.services.immich.port}";
      proxyWebsockets = true;
      recommendedProxySettings = true;
      extraConfig = ''
        client_max_body_size 50000M;
        proxy_read_timeout   600s;
        proxy_send_timeout   600s;
        send_timeout         600s;
      '';
    };
  };

}
