{
  inputs,
  outputs,
  lib,
  pkgs,
  meta,
  modulesPath,
  config,
  ...
}:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
    ./services.nix
  ];

  sops = {
    defaultSopsFile = ../../secrets/joejadserver/default.yaml;
    age.sshKeyPaths = [ "/etc/ssh/ssh_host_ed25519_key" ];
    secrets = {
      borgbackup_passphrase = { };
    };
  };

  nix = {
    package = pkgs.nixVersions.latest;
    extraOptions = ''
      experimental-features = nix-command flakes
    '';
  };

  nixpkgs = {
    overlays = [
      outputs.overlays.additions
      outputs.overlays.unstable
      inputs.alacritty-theme.overlays.default
    ];
    config = {
      permittedInsecurePackages = [ "electron-25.9.0" ];
      allowUnfree = true;
    };
  };

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  services.qemuGuest.enable = lib.mkDefault true;

  fileSystems."/" = lib.mkDefault {
    device = "/dev/disk/by-label/nixos";
    autoResize = true;
    fsType = "ext4";
  };

  networking.hostName = meta.hostname;
  networking.networkmanager.enable = true;

  time.timeZone = "America/Chicago";

  i18n.defaultLocale = "en_US.UTF-8";
  console = {
    font = "Lat2-Terminus16";
    keyMap = "us";
  };

  systemd.tmpfiles.rules = [
    "L+ /usr/local/bin - - - - /run/current-system/sw/bin/"
    "d /var/lib/minecraft 0755 root root - -"
    "d /var/lib/borg/.ssh 0700 borg borg - -"
  ];

  virtualisation.docker = {
    enable = true;
    logDriver = "json-file";
    daemon.settings.features.cdi = true;
    rootless.daemon.settings.features.cdi = true;
  };

  services.openiscsi = {
    enable = true;
    name = "iqn.2016-04.com.open-iscsi:${meta.hostname}";
  };

  users.users.joejad = {
    isNormalUser = true;
    shell = pkgs.zsh;
    extraGroups = [
      "wheel"
      "docker"
    ];
    packages = with pkgs; [
      tree
    ];
    hashedPassword = "$y$j9T$zCosUIu8eNq21sMsgQ7ya.$0oQ.aynDLokO77HvIjV.EEMDrnI25n8VQJgEd3RlSx8";
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDzIbh1w5EeOjFTWaQ9V5PFHf5ipVNQ33sjzpsNDNgfD jade@Jades-MacBook-Pro.local"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPlvznoql2lTnV8qHUE6G35OKEHYKuODHIsfILpo4L98 Generated By Termius"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN6MCnmxn47X/aP9pQxNmHc2I6kkZqh5R+J4KdcJUhZI jade@mini"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOciDf2c/QVPKjPVgSXYg7LSg8nwL4J7JDf8mYO4cs11 iPad"
    ];
  };

  users.groups.borg = { };
  users.users.borg = {
    isSystemUser = true;
    group = "borg";
    home = "/var/lib/borg";
    createHome = true;
    shell = pkgs.bash;
  };

  security.sudo.wheelNeedsPassword = false;
  programs.zsh.enable = true;

  environment.systemPackages = with pkgs; [
    R
    age
    bash
    bind
    cifs-utils
    fluxcd
    fzf
    gcc
    git
    gnumake
    helm
    kubectl
    lazygit
    lua
    lua-language-server
    luajitPackages.luarocks-nix
    nfs-utils
    nil
    nixfmt
    nodejs
    opencode
    postgresql_17
    ripgrep
    samba
    sops
    starship
    stow
    stylua
    tmux
    unstable.cargo
    unstable.neovim
    unstable.rustup
    zoxide
    zsh
    ethtool
    networkd-dispatcher
  ];

  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = false;
      PermitRootLogin = "no";
    };
  };

  services.borgbackup.jobs.joejadserver = {
    paths = [
      "/var/local/vaultwarden/backup"
    ];
    repo = "borg@sorserver:/var/lib/borg/joejadserver";
    encryption = {
      mode = "repokey-blake2";
      passCommand = "cat ${config.sops.secrets.borgbackup_passphrase.path}";
    };
    compression = "zstd,6";
    startAt = "weekly";
    prune.keep = {
      weekly = 3;
    };
    environment = {
      BORG_RSH = "ssh -i /var/lib/borg/.ssh/id_ed25519 -o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=/var/lib/borg/.ssh/known_hosts";
    };
  };

  systemd.services.borg-ssh-keygen = {
    description = "Generate borg SSH key if missing";
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
      User = "borg";
      Group = "borg";
    };
    script = ''
      if [ ! -f /var/lib/borg/.ssh/id_ed25519 ]; then
        install -d -m 700 -o borg -g borg /var/lib/borg/.ssh
        ${pkgs.openssh}/bin/ssh-keygen -t ed25519 -N "" -f /var/lib/borg/.ssh/id_ed25519
      fi
    '';
  };

  services.tailscale.enable = true;
  services.tailscale.useRoutingFeatures = "both";
  networking.firewall.checkReversePath = "loose";
  services = {
    networkd-dispatcher = {
      enable = true;
      rules."50-tailscale" = {
        onState = [ "routable" ];
        script = ''
          ethtool -K ens18 rx-udp-gro-forwarding on rx-gro-list off
        '';
      };
    };
  };

  networking.firewall.enable = false;
  system.stateVersion = "23.11";
}
