#ENC[AES256_GCM,data:AQB/C1Oy8vkTMIAwp24xybHkceegsEUZ3jzCYGrjCGk=,iv:9FRk78F5LPpOZ3MkQmC6L+7Vw54dAtEF0JCQt8h+DIg=,tag:CYdkLz/9dxCOdcoUi9Jcow==,type:comment]
#
#ENC[AES256_GCM,data:QrdHHc/74h8LZ/xaYI8hI4m0GdJmZOytsbEOvs+QyZRS/Meo4IaXhIy+wjsxrag041CDQpMiMBd70q13Sjlxt4xtaiQLKQ==,iv:DnIJRhOFRT2yxC6qk5Lb1imGzm/TipVoW1muRFJfuvU=,tag:D0/dX2Y+zbZSmIg+Yxxaug==,type:comment]
#
#ENC[AES256_GCM,data:YvGhdIX4W5U2N1JAffOZ9UJNsg+1qIS6M4+r5xphFKWCfCBi1AcIyGPsbGrmcFMSl8w=,iv:VDFscRSe3EjwalOLE2U88gr93ECtjP0sEGbdn394jEc=,tag:HPq3uqfyx2rAwfHkR3jdIA==,type:comment]
#ENC[AES256_GCM,data:IGzprFO9qwGNwgCBsrxoMTFpH9PgPp/mOSTpZKpdCEU=,iv:dxdXLxN2TzyMfMzuv4VFSmNveL5jMs5DpAiulQ0CABE=,tag:MuAtH7bhDGcrAnhjoxDBJw==,type:comment]
#ENC[AES256_GCM,data:96Ld2nlK2OwZeDstEPCgBa/AGSAAtXvLHXyU+HS5J2zzQFfhyefdnX4rYXkB8LNRoSat1iQKJRXJgcRIMg==,iv:VwH6B3BOdrXcphJVrgEGayeSf7t5B+ZcZtnJ1NKJKfc=,tag:pRQj72pxQzW3N/IQzIkwjA==,type:comment]
#
#ENC[AES256_GCM,data:00z8QL4uwbkQa8Jynk+ZgCTeZfA9Lk74b9GvEGEiAZPY4w==,iv:3o9J1P4XnoCutsd/IFBE6hHigCKzTdtI/BiaLb9g6ao=,tag:GabQTUsvshucgzNUO9bm5A==,type:comment]
#ENC[AES256_GCM,data:gPDiFxE0f9YE4t1cW+Pita8PWCMUWpXl466CTKQLjTTGEVPFxRU3Lw==,iv:rQU4Pzk/A+aPw6s1zqlIpiTDAW2llkbetAv4Dsk9ECs=,tag:Yyjgq/lRE6C7pQHgxwRtEg==,type:comment]
#
#ENC[AES256_GCM,data:aE2Eptg645AClygt8sQ1E3FMN/V7mw/srA8oR6ZLGKdeN6soW/AsmbetsRxQYAU7e9xFobQoXiyx8sZbp1YSH24vvTWW2w==,iv:vFfEVrxXkZxHtd4l09rYcOiJJgLRcdPAKb6qh6zae54=,tag:2cvK45k1v+kz+i53AozR7Q==,type:comment]
#ENC[AES256_GCM,data:/GVBsLZyYInlavKfzvsyeLX520Mk9SSA1uGEiJbGUlOB4IAct5VKojcb8i9W/lBBLtWk,iv:iaO70j3tIdeAeusWN9m4p55nBfpyfT8IbfQOXnoCPZo=,tag:43f2GZm6CYw9J839PKyz9A==,type:comment]
wireguard_private_key: ENC[AES256_GCM,data://kivfmQQsIgDAUD3q7qlaOYOMgzZffg+DlZYI3c0I+bgLxmw8el9tansTg=,iv:LoKbMPO8xaOc6hgcPm9IS8mKFWFG70et/Tk8X+qfiIs=,tag:xzpKGPsT2FLpqrRiqsFYqA==,type:str]
wireguard_endpoint: ENC[AES256_GCM,data:YeyrzejQUmygwgJwyt9G2tvCMA==,iv:urbqRjNZwd6S9yaj52OpSoiZZrRvtZpAunuWK7iV+ko=,tag:4m+dcvtzXvpWxP5P14njTw==,type:str]
nextcloud_admin_pass: ENC[AES256_GCM,data:ZNpMGi+va63WFNoOUJ/0RKHDPp8=,iv:aAfEuBg0MNOB1CR/jpSsTHrSlauiCYuVcKs98UX0KMQ=,tag:/Wu1M2cMyYJHL6kVilOmDw==,type:str]
borgbackup_passphrase: ENC[AES256_GCM,data:YOosWIHOBkrDa6AlL6TUwc3FqqcwYIQovA==,iv:z1yIoh4ldKlrxfFOPEDBD2qoOzvjp8rfjJk6gd4hsX0=,tag:ctY952Z+0cpXqVgB4AtNuw==,type:str]
#ENC[AES256_GCM,data:oxxaMRmr0Xguol1ybaSfFIg4jvm5UVEYqHsuYs0blUKqZR6znIX9Y9Dox+nw0EoHtfER9mh3whtN7Nlrn8rTRNTW3zHqBCMAQ5L/PQ==,iv:61Yq5Fpfqwdla4eOMelZtufTwDQFqFz+Gh0gf4GymlY=,tag:LFIGyrWb1AbTK3LAUpD/xg==,type:comment]
#ENC[AES256_GCM,data:MlzG3NYd/6PYnc/AZmxnysu/jvwlIeutDrj0EMxVAnax+73Ra6ZmJ1+G+0e1uHQidMBLr6n1,iv:knwYF5XMM10YZIYPVSPxmJJys+0w+mGXpkTmKhoNeWY=,tag:jYzbE8rYtt3szEaByvcivA==,type:comment]
sops:
    age:
        - recipient: age1uukv9jeung20z2vg9msfsw868h0n9qleh89huvrlj7z02dwpk4lsmvnuqh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbU5lc3N0VC80bnpLYlha
            VHpWdHJGQkdsVUxOcys2dnlhTFErUEsxL3hVCnRUeEh4KzVFbTlBNUR1OHU1cW1j
            U2VvNmdGVnUrNFVKb1h5aDIzVFZJT2MKLS0tIHFOUXFncEJrZGpxQVUwcGJyTXVF
            S1U5YnEreE0vREtCUExDdHFrS3NDclUK5+3JL/bKlXKaL849KJcmFdwfSaBjdvXT
            4svkEEHJ/9bMwvLgrub8nGMrx0kKHwxlov7XTmVCg2HyGi/uWn7Riw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T14:06:29Z"
    mac: ENC[AES256_GCM,data:77qPhQC5Y1razbKGL+culfnV+1LcNM7oTQsCKridm5ADFLlcMP2to6jCU1B0s2tpiSK30T3yB8lJY+eo0DbYvYyMgBCMUctwtTPlR4hMkb1OVRUY+W/mNpTaEv3aAoUJ+cRIzPXlrp7M28WvjtPHOLPG+BiIn9BNiX3uiIZ8qP0=,iv:Yz3IAGt/EoyesfXBKDFwHvVKzb8uYmeat0cNsE67jDo=,tag:8Zx9g1/zx6B0CNgCmCYi3Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
