wireguard_private_key: ENC[AES256_GCM,data://kivfmQQsIgDAUD3q7qlaOYOMgzZffg+DlZYI3c0I+bgLxmw8el9tansTg=,iv:LoKbMPO8xaOc6hgcPm9IS8mKFWFG70et/Tk8X+qfiIs=,tag:xzpKGPsT2FLpqrRiqsFYqA==,type:str]
wireguard_endpoint: ENC[AES256_GCM,data:YeyrzejQUmygwgJwyt9G2tvCMA==,iv:urbqRjNZwd6S9yaj52OpSoiZZrRvtZpAunuWK7iV+ko=,tag:4m+dcvtzXvpWxP5P14njTw==,type:str]
nextcloud_admin_pass: ENC[AES256_GCM,data:ZNpMGi+va63WFNoOUJ/0RKHDPp8=,iv:aAfEuBg0MNOB1CR/jpSsTHrSlauiCYuVcKs98UX0KMQ=,tag:/Wu1M2cMyYJHL6kVilOmDw==,type:str]
borgbackup_passphrase: ENC[AES256_GCM,data:YOosWIHOBkrDa6AlL6TUwc3FqqcwYIQovA==,iv:z1yIoh4ldKlrxfFOPEDBD2qoOzvjp8rfjJk6gd4hsX0=,tag:ctY952Z+0cpXqVgB4AtNuw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRTN3OUM4cHdrYU11YWFm
            aXN0azFuUGVHRDJsSWVFTUlLUUZiblR2RFRBCldZSERNc2c2LzRPampPZkFsMGZi
            aEpUSG5jam5sY3BsOVBCSmdwbko4dFEKLS0tIFZEWnJ5QVJpOHJxc1o4R1ZVWCs4
            VzBHT2daK21yRzU4RDZ0SjNlZmZiTGcKcJdaN4vPFj7dUsqdhNP9NtTJi8Ww1ogF
            q8rtrn7NisEI+61v7KVlHlGwEtu/6qBU9DxtBvxSFgH622RPl+qzLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uukv9jeung20z2vg9msfsw868h0n9qleh89huvrlj7z02dwpk4lsmvnuqh
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSkxROW1xNWt5dkNYMUVV
            Y1l1YndTZXNidm9mYjlaY3lpTmxqVHczaWdjCkcxM3JQTDNsOGZla1A5WGtHTFRs
            QWlhTlRNM0xkbTdGVVlBT2t6Vzd6UGsKLS0tIHJyRTFXMkhPeGxXSTRnSGY5SFVO
            Zi9UMmgxWGllb0FCeU0xc0RkbHpxNFEKwU6De4anFc2FvQslOrxttC2wkgLyyrK8
            hE7yvhwvKfCtGCFamUdsVZ5oUGOVoy+y9IlHm5dnzmllZBBezJXUhA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pe2tlqj0lgfdjfrv2ztcgaltgnyt82wdx4dwcgwt85q52l4ujpkq8qcycv
    lastmodified: "2026-06-07T16:29:56Z"
    mac: ENC[AES256_GCM,data:rH7jvfDCSV9o9rYtj/yzLzCOGsWZq+R773xmpWVQxVpTUJLiE7vB8SsQulepIDhfOISu2M06i8Fih8oLK58kmTGaVIo2nNoA34v2doWO2qhHAaQJAx3AsALo8POl+4iCAkqJyDF21Pr9wHZn62Oymq9NqUShc+Q3i2H7gO+874s=,iv:Dg3Vf6sBIrZyCCdIvBuN0a6hsFYYz1OvUwbFdB0TZUM=,tag:nPL7dnfFTL5UWSy5oGKEhA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
