wireguard_private_key: ENC[AES256_GCM,data://kivfmQQsIgDAUD3q7qlaOYOMgzZffg+DlZYI3c0I+bgLxmw8el9tansTg=,iv:LoKbMPO8xaOc6hgcPm9IS8mKFWFG70et/Tk8X+qfiIs=,tag:xzpKGPsT2FLpqrRiqsFYqA==,type:str]
wireguard_endpoint: ENC[AES256_GCM,data:YeyrzejQUmygwgJwyt9G2tvCMA==,iv:urbqRjNZwd6S9yaj52OpSoiZZrRvtZpAunuWK7iV+ko=,tag:4m+dcvtzXvpWxP5P14njTw==,type:str]
nextcloud_admin_pass: ENC[AES256_GCM,data:ZNpMGi+va63WFNoOUJ/0RKHDPp8=,iv:aAfEuBg0MNOB1CR/jpSsTHrSlauiCYuVcKs98UX0KMQ=,tag:/Wu1M2cMyYJHL6kVilOmDw==,type:str]
borgbackup_passphrase: ENC[AES256_GCM,data:vpgh7VybPu7YxeIAPKulPUvZ1uDDRg==,iv:Jk85mP+7DHnv+z3BdJmfGgB2uydSouK2ROmg9oORfRI=,tag:68MUokPssWfOTyIJflxxfw==,type:str]
cloudflared_token: ENC[AES256_GCM,data:Mlrsh3feSMnAUmzUp4SQHf1ZsVA0jyOrr5j+Cc1nn7hE8pkt/s9azZDfZYwvcqahbrcB5pwYSZYGjoJ6hdw0FFvP/+2aUJOc4DMqxjNHi1+42QjhqA3XLA2sQjkIzhCm936A0ECBepZS6JdGvTTDQTm+kwxDb6ZWmknmikkRw6BzVjsGyUS7GPIAh0D8Usc7BDlRKAw8WS5r8HZLPhYKQlnOm8lPkSa7o3SD8UXavWIlHS4WwZC8Vg==,iv:iGydDE5kvWkfDdKPUolxaSgtRnMQ+xNANaerCgIB/a8=,tag:YGceAy1zVBLPQHHZHc302Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRTN3OUM4cHdrYU11YWFm
            aXN0azFuUGVHRDJsSWVFTUlLUUZiblR2RFRBCldZSERNc2c2LzRPampPZkFsMGZi
            aEpUSG5jam5sY3BsOVBCSmdwbko4dFEKLS0tIFZEWnJ5QVJpOHJxc1o4R1ZVWCs4
            VzBHT2daK21yRzU4RDZ0SjNlZmZiTGcKcJdaN4vPFj7dUsqdhNP9NtTJi8Ww1ogF
            q8rtrn7NisEI+61v7KVlHlGwEtu/6qBU9DxtBvxSFgH622RPl+qzLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uukv9jeung20z2vg9msfsw868h0n9qleh89huvrlj7z02dwpk4lsmvnuqh
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSkxROW1xNWt5dkNYMUVV
            Y1l1YndTZXNidm9mYjlaY3lpTmxqVHczaWdjCkcxM3JQTDNsOGZla1A5WGtHTFRs
            QWlhTlRNM0xkbTdGVVlBT2t6Vzd6UGsKLS0tIHJyRTFXMkhPeGxXSTRnSGY5SFVO
            Zi9UMmgxWGllb0FCeU0xc0RkbHpxNFEKwU6De4anFc2FvQslOrxttC2wkgLyyrK8
            hE7yvhwvKfCtGCFamUdsVZ5oUGOVoy+y9IlHm5dnzmllZBBezJXUhA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pe2tlqj0lgfdjfrv2ztcgaltgnyt82wdx4dwcgwt85q52l4ujpkq8qcycv
    lastmodified: "2026-09-12T15:34:09Z"
    mac: ENC[AES256_GCM,data:1FmncDrrO/TPE18gNpuq6EeYImbF28LcybEMqXKLYhUc+CRvcE3pNEAGvJju+SewlVG96N8NPqjFc/SEMra/yPq6PzSjM4MjJujLXYm1rEqwhI5qP++bUpL52CMoFi4IREP1qVgm2XNb4A3lTR0WBov3L3lZrGIB5P1AfkMYWW4=,iv:009c92Q2/ANNBi3gebL4NB6Cq/oK4oSMB4p2Iqhf8Wo=,tag:clXdQuONPYNrNMU9Hvl+gw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
