{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.dotfiles.jade;

  defaultAuthorizedKeys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDzIbh1w5EeOjFTWaQ9V5PFHf5ipVNQ33sjzpsNDNgfD jade@Jades-MacBook-Pro.local"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPlvznoql2lTnV8qHUE6G35OKEHYKuODHIsfILpo4L98 Generated By Termius"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN6MCnmxn47X/aP9pQxNmHc2I6kkZqh5R+J4KdcJUhZI jade@mini"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOciDf2c/QVPKjPVgSXYg7LSg8nwL4J7JDf8mYO4cs11 iPad"
  ];
in
{
  options.dotfiles.jade = {
    enable = lib.mkEnableOption "Jade's user account";

    hashedPassword = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = "Host-specific hashed password for the jade user.";
    };

    extraGroups = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [
        "wheel"
        "docker"
      ];
      description = "Groups for the jade user.";
    };

    authorizedKeys = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = defaultAuthorizedKeys;
      description = "Base SSH authorized keys for the jade user.";
    };

    extraAuthorizedKeys = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      description = "Host-specific extra SSH authorized keys for the jade user.";
    };
  };

  config = lib.mkIf cfg.enable {
    users.users.jade = {
      isNormalUser = true;
      shell = pkgs.zsh;
      extraGroups = cfg.extraGroups;
      openssh.authorizedKeys.keys = cfg.authorizedKeys ++ cfg.extraAuthorizedKeys;
    }
    // lib.optionalAttrs (cfg.hashedPassword != null) {
      inherit (cfg) hashedPassword;
    };
  };
}
