acme_cloudflare_env: ENC[AES256_GCM,data:C9pi/WMrKGkKbHyn2tS23ioO/FyPyqNb7/Xq2fFSfL9CHkCtqeIBuanO7O0BGJlE2tIIM2UjV9wYN7HcaJriSeA031r6eCaHrWTA1ft1jg==,iv:axajU3Sz/YUhkDbaBRD/Il4tKf983jxzPq+D/ixI3pg=,tag:IAyk1MCMBRiof5Vv1jGjkg==,type:str]
vaultwarden_env: ENC[AES256_GCM,data:jMVjm1tbqoHfDyaRq0tJZpZDIOHa4GzRJn5gqhjlVfSynUz9KVoCW4YTm4SXGpaaIRbLCb6A42q224MtYKJYkAl3N2TQxD9zIwazD2qfDGt0HH+MhSoPEkS1JdcBJycRDCQg4bkFDNMDPsyF9anqj+lCjRNyO1RpzmnxdcRLJRHJ7wGNCXz8rlu7vFxLNO435bp1Q5zhqvQZndPL543kC7akfuDrTpGntYGVNXDQ5Lh7MVWDG3JsHkJBEDgIbMZTXIMXLQizo8ja5uMHGpCJeR62juJ/eDVB0VJp43Yuhc4bVM7ZzuxRL3JJXNhCc6ZwWLqz0MpRqTFiblulz4ctK2qKjHIOCTc3HARnbFIScb3gTNuhgsjQ7Y7s/06KXJPdQvmnDGULE+jwJmXFbXDRjoBY6kNMsgjRrMJT1UoxicnG+9Kcg5ZXG+o3t52XoEa5vFJt7t/PXQ==,iv:i+iOHnQVGwU1JXJrNWQl9/xjsls+icFytM+p8Ujbg4U=,tag:/37i8gjuft24ME1tRqAFKw==,type:str]
sops:
    age:
        - recipient: age17q4u0f0p82l97e2lsvdklxcsp699ynsr6d3xd8rkupsssq3p3sxql6fdhn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCS0VEcXZxam9hUllYRjFm
            WStIeUhvL3IyZzM0OE5Qa0NtaE5UVGhQTHlJCjhLU1JpemNnRXBVVlpERGZvRVdC
            Zk0rSGlTMzY2R3dGNnQ0Wm92MUNITmsKLS0tIDlwNlpKL3BTWDZ0RG5GbWFYbzhW
            RWlRNm1TdWNHUyttSzlaTEUxcTVoV2MKlHlSogUl09z4pp+pijhNXKds3pXaPKoy
            spZkWA6I0D3Q2qjYklpesVxWE+ySWNwhwKBLgawQlNE2IcgqFX++qw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pe2tlqj0lgfdjfrv2ztcgaltgnyt82wdx4dwcgwt85q52l4ujpkq8qcycv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NkFUZ28vUVlCc3lQeHRI
            aVo0bkk0NVFWR0plaU1sS3RqQnA4UmN6T0E0CjUyaXFyZzBKYjJVNHhaL2dGejI1
            RXdLTVVKc29TbCs5YVZJSVNJK1JvS0EKLS0tIHI3T1FKRTZ5Z0ZLNTdLQVlGMmY2
            WXF4T1V1M05YZmhzVjU4V3cvVEFXbncKBQb8LeCsohLeXD8ryv/+lhWEBvf3XWlk
            Nnn0suDn4jhdgrGCmYDZ+lPavpXcbkEudZGzVFOszxDRnGjBTE/HPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T15:48:16Z"
    mac: ENC[AES256_GCM,data:P/GTDs4NNDPVjUgxMZJ2pjBwVa/8xQ+S0/v2cuI8f6RBdD2x4TCZx3jZjN0F83TottHv+0KtrZFKEkvpTd8S1xNforquZwpQ5lt1SYlQcHgnwNl5VASYX3sfkvwimmtFPMTWtGRCcu7mJ9B67tsw9eDlkjix0mxsP2q7FKYI7jk=,iv:Cez01NZkEdGvZc5hvwcDEmUn1FYFFwdUvNvdEC1pjys=,tag:zkjYi+NDz7aAFnsRB9wG2A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
