acme_cloudflare_env: ENC[AES256_GCM,data:+na03e9YkeaAcGgZ7DAcoSXQlazBQNG+hKXdDcdlVbKfn8I3LcLyflLGvX6ymPjWcc3e64P7DFREC1ZoJkAidhPkSyn2JI+yjF5dD1j8Sw==,iv:DE1eWpt6NKN+hWM1Bgy2pqHpcOQK9RhEvuXZkQUDHok=,tag:Yu/ixFuKFytTvKznmNZerQ==,type:str]
vaultwarden_env: ENC[AES256_GCM,data:3+BMNKCzr/GOChFloJnPZPWDE3Dj8nSmesOj33grvn6bibb0Pr5JktEoDYwnbCd8iOV+SsbJu8LFW3zZNKQ2kCcfkiYp8a5xI4yE3aw+tr93vBLu9pfdcYgrQ0+Sfa/a91RzkrGaZmwPIDoXND3w2LGY0oyn+iHj34hAeWEgzg6hFSE3fvM6Kp+Kv74cRl8uYplW8gZGFRExbPEmcPj222n2X7l+Wu0Hp9uKoLn5vxYYiyTnG7X5cwhS8KfV8cwJk7iagc8Ua8yhPLTmvPxUE/By84zG97ExN/HKejrgqT6uBlKl3WtcMaLSiwTIBRFdNscuCeBtkSofscyCCGYB7VQAozHNRMBb4f1WbKPvNU7vUEoJQGXgTP/4CiSOU7RhxVaBDhDTClQJ/CzuwUlQ0FBvufCpCeWGJJT2iwWpYDtNF9rLsOVRkuGI617mVVK4jGd4TTyd1w==,iv:IUSwY78Xl+mxvNi8CkscZbf5r7wFiBbb30gtYD6NYLk=,tag:5J7rNsTcKExI2pDK6l/LZw==,type:str]
freshrss_pass: ENC[AES256_GCM,data:CqHSwvHahrvL52rya7Y=,iv:FBgV0+97QFrflgd9SKyv1JUdkPjbESBjN0CYPstKDQM=,tag:/7JwiTVL62MRi+baV2/V8w==,type:str]
running_env: ENC[AES256_GCM,data:LdiR7ZkdMIFl2QSHYtxDoAthYxjvRRM6zBs=,iv:J6WMCcDCdv1on/poLo+VDFdm+UUCGLii+N1mImC9vf8=,tag:5op4odh2NeonEDFrpljzNQ==,type:str]
workout_env: ENC[AES256_GCM,data:heBjIlIdeZ0hA0Qev5ns1+F9tP/UcncyJX8=,iv:5b3nmo3vQ5CTjrRKXGapVnyT07bQXDJzNIItEcEQDpQ=,tag:AFYocueIwm5ksU512cpSqA==,type:str]
sops:
    age:
        - recipient: age17q4u0f0p82l97e2lsvdklxcsp699ynsr6d3xd8rkupsssq3p3sxql6fdhn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWmljRDN1ZmhQQzBqT0Zs
            YnNyMm03c3lMajVtS2kyT1B1NVRFWkQycVJVCnNSMWJMQzhyeTRkalRzd0hJclFp
            RkZ6VHRnb1JQNEpHWjFFc0pGTy9xTG8KLS0tIEhFbkJ1VUk1bGg0Slo3bnJjaWk3
            ZTFza2lTN0NLUEVwUmNuSzB3VVJlb1EK85e79fhZwvk6csLjXk0mzisJ9C0sIm9+
            boD/kb54ELq1GCcBqOyO63nrm41sTuCboEJIiokahcOKdckaNhG3Cw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pe2tlqj0lgfdjfrv2ztcgaltgnyt82wdx4dwcgwt85q52l4ujpkq8qcycv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZG94NFRkVXQzNFhKV0xj
            QURsVFR2azFtaVQ1RnkvbGMyYkxjM1FrbGdrCk52NlNzRDIxSzZTY1hzU0dXTnlT
            SnRBejUrTk5pc1QxOEpaZzdhWlNTOW8KLS0tIFo2d0hZeHhVRnJqeHRVSmlRTEVm
            dDlSbVBlZ043OS9QVTZGUUtsTXpWV1UKkku1bpoS8FBK+sybVl6GrkVOJ7h4biTT
            ascqX1ZCrQYlUpJ9JG0ccCE7cQMFc/fZ0SscrYb3kIz/ANqsvfrT6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T15:25:32Z"
    mac: ENC[AES256_GCM,data:oOPASmNzLdUgx/XzUUfnrhYnj8BqktmVs6hRheJplTR1Nw4dQrlPzMzf2bvrJHzdJDKdVYcUz1Qm56iJ+ZDEQRSWKZWtjVkMrl8++xOD85zf1bc8ibz3Lrmr5+Wu+DaGiMcgq4KA1MRv7yzcirdBpjEYUXnzYnIPKyNiY+lbK2k=,iv:uuZLs43gjAbNez5S55jDm6wk+bO82lYh0OkQzHmvrJQ=,tag:VlzXnxkyTwSDQJBfLqRi/A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
