acme_cloudflare_env: ENC[AES256_GCM,data:+na03e9YkeaAcGgZ7DAcoSXQlazBQNG+hKXdDcdlVbKfn8I3LcLyflLGvX6ymPjWcc3e64P7DFREC1ZoJkAidhPkSyn2JI+yjF5dD1j8Sw==,iv:DE1eWpt6NKN+hWM1Bgy2pqHpcOQK9RhEvuXZkQUDHok=,tag:Yu/ixFuKFytTvKznmNZerQ==,type:str]
vaultwarden_env: ENC[AES256_GCM,data:3+BMNKCzr/GOChFloJnPZPWDE3Dj8nSmesOj33grvn6bibb0Pr5JktEoDYwnbCd8iOV+SsbJu8LFW3zZNKQ2kCcfkiYp8a5xI4yE3aw+tr93vBLu9pfdcYgrQ0+Sfa/a91RzkrGaZmwPIDoXND3w2LGY0oyn+iHj34hAeWEgzg6hFSE3fvM6Kp+Kv74cRl8uYplW8gZGFRExbPEmcPj222n2X7l+Wu0Hp9uKoLn5vxYYiyTnG7X5cwhS8KfV8cwJk7iagc8Ua8yhPLTmvPxUE/By84zG97ExN/HKejrgqT6uBlKl3WtcMaLSiwTIBRFdNscuCeBtkSofscyCCGYB7VQAozHNRMBb4f1WbKPvNU7vUEoJQGXgTP/4CiSOU7RhxVaBDhDTClQJ/CzuwUlQ0FBvufCpCeWGJJT2iwWpYDtNF9rLsOVRkuGI617mVVK4jGd4TTyd1w==,iv:IUSwY78Xl+mxvNi8CkscZbf5r7wFiBbb30gtYD6NYLk=,tag:5J7rNsTcKExI2pDK6l/LZw==,type:str]
freshrss_pass: ENC[AES256_GCM,data:CqHSwvHahrvL52rya7Y=,iv:FBgV0+97QFrflgd9SKyv1JUdkPjbESBjN0CYPstKDQM=,tag:/7JwiTVL62MRi+baV2/V8w==,type:str]
running_env: ENC[AES256_GCM,data:QXeg+u8pfAuNYh3LyLkgqS9N/cdqVIdRHVmEMz6RIf4JC9EjOz3M7WxffvEwpJGv2Ab8A9KP9zjoJ4/wDLVpb+4+VQ6swqmGlg==,iv:uE7Y8DJdUVmwHzDhyx2bK/qTUPc4wxPccNjxW/LLYOY=,tag:J26g9rpG/s5bVB7gK5AB3Q==,type:str]
workout_env: ENC[AES256_GCM,data:leIAAIY/F0zUU8b0NY0+YRFZ3M+Aj9vJ3nnT8r9519XA3MiQQjC3Ing1jQB45giM4gZlU864cIkZwO8oC1mYmB8sU/xWTF/h+w==,iv:LN0uXL+jy0xN2alpOF6dHl/hK2SXeuSGhvN63fpZGyY=,tag:L535F6cA8cq6tey4Avxfhw==,type:str]
stock_env: ENC[AES256_GCM,data:j5YzSbC3GEYvJwjR/Y+y62wp3exWBlZF/pUB+4HRb7+z1ceDdhXaXusy/Cmt9vOSBeBvervvahnP8td5TIajKi7pxfjh0G3RKjzGXbKGoutVjphYssr74zC+sal0GmetfXPsRgY0MIw45REzontG/KEtWUm1VFJCYA5qi6WpytB/+swV+l69uGMrNu4RZ1CZ,iv:iTAdpbALXMC4LNBq63qVjxSjlmp2btYMOB6NN3e4cLI=,tag:inx/KU8o8ILuMM7VTqRI3Q==,type:str]
nordvpn_wireguard_private_key: ENC[AES256_GCM,data:3qWidJwJLB1ZBpv6gAalfwg3ALdgYXXCngmIwRkBSxSbJ+z8fA2RScun06Y=,iv:9wlvbqdZfW9eCg25Vyoa4ZpWRYF/kFvgDCIRaHz9YXs=,tag:x7zKOSSu3senKKGKkIvOTQ==,type:str]
nordvpn_wireguard_endpoint: ENC[AES256_GCM,data:SlUa63tFjOtRYkWQlXvNiMz1ew==,iv:ITui+RR4paQIQfxduKpaMrwqUYZ2rQyIAjA74hERQOU=,tag:2oF+OuMCItaq6NE+gYYscg==,type:str]
nextcloud_admin_pass: ENC[AES256_GCM,data:W/CsiM6vnrHM61RJfhQ3jzjU51Q=,iv:VS4nWts6SqdVf2hKxbWLcJONvqH7dJZ7pxsegO7Hhdo=,tag:6T8HOj5koNHOm8pPcsy0aA==,type:str]
cloudflared_creds: ENC[AES256_GCM,data:WUK8X8dbmrfjdk+csWz8n16HNZkyB4pSKklE+Vp0p+lveqkEHaSRpfLN+n3QOFKi4iyQ1Fb9fsxfM8Z8bmgfhFgJ8dZblHLXk/CADaoYdS0N8tVyHODUN5pzwt3/vXR/o+X9n6pfJ0RDHUdsbxLxXu8PZsmRA//XasheHmQX4AM3Qo/Jg6+iGkhSqVu5+4TvFeXJ1WTZE9WbgXUnFSu02KRBecJlYV1WBkq3KjW17Q==,iv:ubsmN9aYweXQ5FQJke1gxvQhj/AQrY/8J7uUXp2Hk30=,tag:6hsLBehrYNn49aMwCVWnJQ==,type:str]
syncthing_pass: ENC[AES256_GCM,data:uokjleYlejq6FQU3DM5ccEhQHDM=,iv:aYK6VWU7YqLhsct1/MsSqkpvIl/nK0fsngVHUfSZxTM=,tag:MKfFFs853Cwt2TsNIlxzIQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWmljRDN1ZmhQQzBqT0Zs
            YnNyMm03c3lMajVtS2kyT1B1NVRFWkQycVJVCnNSMWJMQzhyeTRkalRzd0hJclFp
            RkZ6VHRnb1JQNEpHWjFFc0pGTy9xTG8KLS0tIEhFbkJ1VUk1bGg0Slo3bnJjaWk3
            ZTFza2lTN0NLUEVwUmNuSzB3VVJlb1EK85e79fhZwvk6csLjXk0mzisJ9C0sIm9+
            boD/kb54ELq1GCcBqOyO63nrm41sTuCboEJIiokahcOKdckaNhG3Cw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17q4u0f0p82l97e2lsvdklxcsp699ynsr6d3xd8rkupsssq3p3sxql6fdhn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZG94NFRkVXQzNFhKV0xj
            QURsVFR2azFtaVQ1RnkvbGMyYkxjM1FrbGdrCk52NlNzRDIxSzZTY1hzU0dXTnlT
            SnRBejUrTk5pc1QxOEpaZzdhWlNTOW8KLS0tIFo2d0hZeHhVRnJqeHRVSmlRTEVm
            dDlSbVBlZ043OS9QVTZGUUtsTXpWV1UKkku1bpoS8FBK+sybVl6GrkVOJ7h4biTT
            ascqX1ZCrQYlUpJ9JG0ccCE7cQMFc/fZ0SscrYb3kIz/ANqsvfrT6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pe2tlqj0lgfdjfrv2ztcgaltgnyt82wdx4dwcgwt85q52l4ujpkq8qcycv
    lastmodified: "2026-06-04T21:57:35Z"
    mac: ENC[AES256_GCM,data:2ar+OABJWbHFN4SvYl9FMI/6fH6rjZS5gU1cS1EAO0UoGkP/KUBBWgopYhNGlw6voLl1qbTFPpfHlAaUH75H9Ijz4Xlg2qtMCYQugqGsIWZJ44eh3cr+WfVWHJxf6uSm7hzIvPO2MDc/xxdYRnA2CL9qz91zvoeGquuTOIfmATk=,iv:HCqvRrqhcw79zTPzswvCW3DsAmAxovcEzy0OredenWE=,tag:ouOB0jcJvumrJx1BqEQZjQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
