{
  inputs,
  outputs,
  lib,
  pkgs,
  meta,
  modulesPath,
  config,
  ...
}:

let
  dotfilesPath = "/home/jade/.dotfiles";
in
{
  nix = {
    package = pkgs.nixVersions.latest;
    extraOptions = ''
      experimental-features = nix-command flakes
    '';
  };

  imports = [
    ./homelab.nix
    ./external.nix
    ./personal.nix
  ];

  sops = {
    defaultSopsFile = ../../secrets/mjolnir/default.yaml;
    age.sshKeyPaths = [ "/etc/ssh/ssh_host_ed25519_key" ];
    secrets = {
      acme_cloudflare_env = { };
      freshrss_pass = {
        owner = "freshrss";
        group = "freshrss";
        mode = "0400";
      };
      nordvpn_wireguard_private_key = { };
      nordvpn_wireguard_endpoint = { };
      vaultwarden_env = { };
      nextcloud_admin_pass = { };
      cloudflared_creds = { };
      syncthing_pass = { };
      borgbackup_passphrase = { };
    };
  };

  nixpkgs = {
    overlays = [
      outputs.overlays.additions
      outputs.overlays.unstable
      inputs.alacritty-theme.overlays.default
    ];
    config = {
      permittedInsecurePackages = [ "electron-25.9.0" ];
      allowUnfree = true;
    };
  };

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  networking.hostName = meta.hostname;
  networking.networkmanager.enable = true;
  networking.networkmanager.unmanaged = [
    "interface-name:vpn0"
    "interface-name:vpn1"
  ];
  networking.search = [ "joejad.lan" ];
  networking.nameservers = [ "127.0.0.1" ];
  networking.enableIPv6 = false;

  time.timeZone = "America/Chicago";
  i18n.defaultLocale = "en_US.UTF-8";
  console = {
    font = "Lat2-Terminus16";
    keyMap = "us";
  };

  fileSystems."/mnt/data" = {
    device = "/dev/disk/by-uuid/036cff31-c5f3-4834-a626-07184f27055b";
    fsType = "ext4";
    options = [
      "defaults"
      "nofail"
    ];
  };

  systemd.tmpfiles.rules = [
    "L+ /usr/local/bin - - - - /run/current-system/sw/bin/"
    "d /var/lib/borg/.ssh 0700 borg borg - -"
  ];

  systemd.services.update-nix-inputs = {
    description = "Update Nix flake inputs";
    path = [
      pkgs.bash
      pkgs.coreutils
      pkgs.git
      pkgs.nix
      pkgs.openssh
    ];
    serviceConfig = {
      Type = "oneshot";
      User = "jade";
      Environment = "HOME=/home/jade";
      WorkingDirectory = dotfilesPath;
      ExecStart = "${dotfilesPath}/scripts/update-nix-inputs";
    };
  };

  systemd.timers.update-nix-inputs = {
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnCalendar = "Sat *-*-* 23:30:00";
      RandomizedDelaySec = "30min";
      Persistent = true;
    };
  };

  virtualisation.docker = {
    enable = true;
    storageDriver = "btrfs";
    logDriver = "json-file";
    daemon.settings.features.cdi = true;
    rootless.daemon.settings.features.cdi = true;
  };

  users.users.jade = {
    isNormalUser = true;
    shell = pkgs.zsh;
    extraGroups = [
      "wheel"
      "docker"
    ];
    packages = with pkgs; [
      tree
    ];
    hashedPassword = "$6$sDfLSHBDw34Mi75P$VZSvinODReSBLOAzjMqdjnY9bftEs1AwOOzZioZ4Pco86hGOFE.UKzrmAopU4zS6w.5Env15XgB5Lds1DqRjc0";
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDzIbh1w5EeOjFTWaQ9V5PFHf5ipVNQ33sjzpsNDNgfD jade@Jades-MacBook-Pro.local"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPlvznoql2lTnV8qHUE6G35OKEHYKuODHIsfILpo4L98 Generated By Termius"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFmO691Ujio3I1tNUGEnSnyhjl0vLCBNi3Q/u0P+UvEX joejad@joejadserver"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN6MCnmxn47X/aP9pQxNmHc2I6kkZqh5R+J4KdcJUhZI jade@mini"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOciDf2c/QVPKjPVgSXYg7LSg8nwL4J7JDf8mYO4cs11 iPad"
    ];
  };

  users.groups.borg = { };
  users.users.borg = {
    isSystemUser = true;
    group = "borg";
    home = "/var/lib/borg";
    createHome = true;
    shell = pkgs.bash;
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMDQXSAmgoIWDeMwrjqNpuEuLE8NJ7oRYdER5V7dkQ4t borg@sorserver"
    ];
  };

  systemd.services.borg-ssh-keygen = {
    description = "Generate borg SSH key if missing";
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
      User = "borg";
      Group = "borg";
    };
    script = ''
      if [ ! -f /var/lib/borg/.ssh/id_ed25519 ]; then
        install -d -m 700 -o borg -g borg /var/lib/borg/.ssh
        ${pkgs.openssh}/bin/ssh-keygen -t ed25519 -N "" -f /var/lib/borg/.ssh/id_ed25519
      fi
    '';
  };

  services.borgbackup.jobs.mjolnir = {
    paths = [
      "/var/lib/nextcloud"
      "/var/lib/immich"
      "/var/lib/db_backups"
      "/var/local/vaultwarden/backup"
      "/var/lib/freshrss"
      "/var/lib/uptime-kuma"
      "/home/jade/.config/syncthing"
      "/var/lib/jellyfin"
      "/var/lib/prowlarr"
      "/var/lib/radarr/.config/Radarr"
      "/var/lib/sonarr/.config/NzbDrone"
      "/var/lib/readarr"
      "/var/lib/lidarr/.config/Lidarr"
      "/var/lib/jellyseerr"
      "/var/lib/deluge"
    ];
    repo = "borg@sorserver:/var/lib/borg/mjolnir";
    encryption = {
      mode = "repokey-blake2";
      passCommand = "cat ${config.sops.secrets.borgbackup_passphrase.path}";
    };
    compression = "zstd,6";
    startAt = "weekly";
    prune.keep = {
      weekly = 7;
    };
    environment = {
      BORG_RSH = "ssh -i /var/lib/borg/.ssh/id_ed25519 -o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=/var/lib/borg/.ssh/known_hosts";
    };
  };

  security.sudo.wheelNeedsPassword = false;
  programs.zsh.enable = true;

  environment.systemPackages = with pkgs; [
    R
    age
    basedpyright
    bash
    bind
    borgbackup
    cargo
    cifs-utils
    cloudflared
    ethtool
    fluxcd
    fzf
    gcc
    git
    gnumake
    helm
    jq
    kubectl
    lazygit
    lemminx
    lua
    lua-language-server
    luajitPackages.luarocks-nix
    neovim
    networkd-dispatcher
    nfs-utils
    nil
    nixfmt
    nodejs
    opencode
    postgresql_18
    ripgrep
    ruff
    rustup
    samba
    sops
    starship
    stow
    stylua
    tmux
    tree-sitter
    vscode-json-languageserver
    yaml-language-server
    zoxide
    zsh
  ];

  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = false;
      PermitRootLogin = "no";
    };
  };

  networking.firewall.enable = false;
  system.stateVersion = "25.11";

  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver
      intel-compute-runtime
      vpl-gpu-rt
    ];
  };
  hardware.nvidia = {
    modesetting.enable = true;
    open = true;
  };

  services.xserver.videoDrivers = [ "nvidia" ];

  services.unbound = {
    enable = true;
    settings = {
      server = {
        interface = [ "0.0.0.0" ];
        do-ip6 = false;
        access-control = [
          "127.0.0.1/32 allow"
          "10.3.0.0/24 allow"
          "10.10.10.0/24 allow"
          "10.26.27.0/24 allow"
          "10.47.59.0/24 allow"
        ];
        private-domain = [ "joejad.lan" ];
        domain-insecure = [ "joejad.lan" ];
        local-zone = "\"joejad.com.\" redirect";
        local-data = [
          "\"joejad.com. IN A 10.3.0.2\""
        ];
        module-config = "'respip validator iterator'";
      };
      forward-zone = [
        {
          name = "joejad.lan.";
          forward-addr = [
            "10.3.0.1"
          ];
        }
        {
          name = ".";
          forward-tls-upstream = "yes";
          forward-addr = [
            "1.1.1.1@853#cloudflare-dns.com"
            "8.8.8.8@853#dns.google.com"
          ];
        }
      ];
      rpz = [
        {
          name = "hageziPro";
          url = "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/rpz/pro.txt";
        }
      ];
    };
  };

  security.acme = {
    acceptTerms = true;
    defaults.email = "joejadjavajim@icloud.com";
    certs = {
      "joejad.com" = {
        dnsProvider = "cloudflare";
        dnsPropagationCheck = true;
        environmentFile = config.sops.secrets.acme_cloudflare_env.path;
        group = "nginx";
        domain = "*.joejad.com";
        extraDomainNames = [ "joejad.com" ];
        dnsResolver = "1.1.1.1:53";
      };
    };
  };

  services.nginx = {
    enable = true;
    recommendedGzipSettings = true;
    recommendedOptimisation = true;
    recommendedProxySettings = true;
    recommendedTlsSettings = true;
  };

}
