{
  inputs,
  outputs,
  lib,
  pkgs,
  meta,
  modulesPath,
  config,
  ...
}:

{
  nix = {
    package = pkgs.nixVersions.latest;
    extraOptions = ''
      experimental-features = nix-command flakes
    '';
  };

  # imports = [
  #   ./homelab.nix
  # ];

  # sops = {
  #   defaultSopsFile = ../../secrets/mjolnir/default.yaml;
  #   age.sshKeyPaths = [ "/etc/ssh/ssh_host_ed25519_key" ];
  #   secrets = {
  #     nextcloud_admin_pass = { };
  #     borgbackup_passphrase = { };
  #   };
  # };

  nixpkgs = {
    overlays = [
      outputs.overlays.additions
      outputs.overlays.unstable
      inputs.alacritty-theme.overlays.default
    ];
    config = {
      permittedInsecurePackages = [ "electron-25.9.0" ];
      allowUnfree = true;
    };
  };

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  networking.hostName = meta.hostname;
  networking.networkmanager.enable = true;
  # networking.networkmanager.dns = "systemd-resolved";
  # networking.resolvconf.enable = true;
  # networking.resolvconf.useLocalResolver = true;
  # networking.search = [ "joejad.lan" ];
  # networking.nameservers = [
  #   "127.0.0.1"
  # ];

  time.timeZone = "America/Chicago";
  i18n.defaultLocale = "en_US.UTF-8";
  console = {
    font = "Lat2-Terminus16";
    keyMap = "us";
  };

  systemd.tmpfiles.rules = [
    "L+ /usr/local/bin - - - - /run/current-system/sw/bin/"
    # "d /var/lib/borg/.ssh 0700 borg borg - -"
  ];

  virtualisation.docker = {
    enable = true;
    storageDriver = "btrfs";
    logDriver = "json-file";
    daemon.settings.features.cdi = true;
    rootless.daemon.settings.features.cdi = true;
  };

  users.users.jade = {
    isNormalUser = true;
    shell = pkgs.zsh;
    extraGroups = [
      "wheel"
      "docker"
    ];
    packages = with pkgs; [
      tree
    ];
    hashedPassword = "$6$sDfLSHBDw34Mi75P$VZSvinODReSBLOAzjMqdjnY9bftEs1AwOOzZioZ4Pco86hGOFE.UKzrmAopU4zS6w.5Env15XgB5Lds1DqRjc0";
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDzIbh1w5EeOjFTWaQ9V5PFHf5ipVNQ33sjzpsNDNgfD jade@Jades-MacBook-Pro.local"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPlvznoql2lTnV8qHUE6G35OKEHYKuODHIsfILpo4L98 Generated By Termius"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFmO691Ujio3I1tNUGEnSnyhjl0vLCBNi3Q/u0P+UvEX joejad@joejadserver"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN6MCnmxn47X/aP9pQxNmHc2I6kkZqh5R+J4KdcJUhZI jade@mini"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOciDf2c/QVPKjPVgSXYg7LSg8nwL4J7JDf8mYO4cs11 iPad"
    ];
  };

  security.sudo.wheelNeedsPassword = false;
  programs.zsh.enable = true;

  environment.systemPackages = with pkgs; [
    R
    age
    basedpyright
    bash
    bind
    cargo
    cifs-utils
    ethtool
    fluxcd
    fzf
    gcc
    git
    gnumake
    helm
    kubectl
    lazygit
    lemminx
    lua
    lua-language-server
    luajitPackages.luarocks-nix
    neovim
    networkd-dispatcher
    nfs-utils
    nil
    nixfmt
    nodejs
    opencode
    postgresql_18
    ripgrep
    ruff
    rustup
    samba
    sops
    starship
    stow
    stylua
    tmux
    tree-sitter-cli
    vscode-json-languageserver
    yaml-language-server
    zoxide
    zsh
  ];

  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = false;
      PermitRootLogin = "no";
    };
  };

  networking.firewall.enable = false;
  system.stateVersion = "25.11";

  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver
    ];
    # nvidia-container-toolkit.enable = true;
    # nvidia = {
    #   modesetting.enable = true;
    #   powerManagement.enable = true;
    #   open = true;
    # };
  };

  # services.tailscale.enable = true;
  # services.tailscale.useRoutingFeatures = "both";
  # services.tailscale.extraUpFlags = [ "--accept-dns=false" ];
  # networking.firewall.checkReversePath = "loose";
  # services = {
  #   networkd-dispatcher = {
  #     enable = true;
  #     rules."50-tailscale" = {
  #       onState = [ "routable" ];
  #       script = ''
  #         ethtool -K enp5s0 rx-udp-gro-forwarding on rx-gro-list o
  #       '';
  #     };
  #   };
  # };

  # services.unbound = {
  #   enable = true;
  #   settings = {
  #     server = {
  #       interface = [ "0.0.0.0" ];
  #       access-control = [
  #         "127.0.0.1/32 allow"
  #         "192.168.86.0/24 allow"
  #       ];
  #       private-domain = [ "joejad.lan" ];
  #       domain-insecure = [ "joejad.lan" ];
  #       local-zone = "\"sorenson-fam.com.\" redirect";
  #       local-data = [
  #         "\"sorenson-fam.com. IN A 192.168.86.3\""
  #         "\"sorenson-fam.com. IN AAAA ::ffff:192.168.86.3\""
  #       ];
  #     };
  #     forward-zone = [
  #       {
  #         name = "joejad.lan.";
  #         forward-addr = [
  #           "10.10.10.1"
  #         ];
  #       }
  #       {
  #         name = ".";
  #         forward-tls-upstream = "yes";
  #         forward-addr = [
  #           "1.1.1.1@853#cloudflare-dns.com"
  #           "8.8.8.8@853#dns.google.com"
  #         ];
  #       }
  #     ];
  #   };
  # };

  # security.acme = {
  #   acceptTerms = true;
  #   defaults.email = "joejadjavajim@icloud.com";
  #   certs = {
  #     "sorenson-fam.com" = {
  #       dnsProvider = "cloudflare";
  #       dnsPropagationCheck = true;
  #       environmentFile = "/var/lib/acme/.secrets/cert.env";
  #       group = "nginx";
  #       domain = "*.sorenson-fam.com";
  #       extraDomainNames = [ "sorenson-fam.com" ];
  #     };
  #   };
  # };

  # services.nginx.enable = true;

  # services.immich = {
  #   enable = true;
  #   port = 2283;
  #   accelerationDevices = [ "/dev/dri/renderD128" ];
  # };
  # users.users.immich.extraGroups = [
  #   "video"
  #   "render"
  # ];

  # services.nginx.virtualHosts."immich.sorenson-fam.com" = {
  #   useACMEHost = "sorenson-fam.com";
  #   forceSSL = true;
  #   locations."/" = {
  #     proxyPass = "http://[::1]:${toString config.services.immich.port}";
  #     proxyWebsockets = true;
  #     recommendedProxySettings = true;
  #     extraConfig = ''
  #       client_max_body_size 50000M;
  #       proxy_read_timeout   600s;
  #       proxy_send_timeout   600s;
  #       send_timeout         600s;
  #     '';
  #   };
  # };

}
