{
  inputs,
  outputs,
  lib,
  pkgs,
  meta,
  modulesPath,
  config,
  ...
}:

{
  nix = {
    package = pkgs.nixVersions.latest;
    extraOptions = ''
      experimental-features = nix-command flakes
    '';
  };

  imports = [
    ./homelab.nix
    ./external.nix
  ];

  sops = {
    defaultSopsFile = ../../secrets/mjolnir/default.yaml;
    age.sshKeyPaths = [ "/etc/ssh/ssh_host_ed25519_key" ];
    secrets = {
      acme_cloudflare_env = { };
      vaultwarden_env = { };
    };
  };

  nixpkgs = {
    overlays = [
      outputs.overlays.additions
      outputs.overlays.unstable
      inputs.alacritty-theme.overlays.default
    ];
    config = {
      permittedInsecurePackages = [ "electron-25.9.0" ];
      allowUnfree = true;
    };
  };

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  networking.hostName = meta.hostname;
  networking.networkmanager.enable = true;
  networking.search = [ "joejad.lan" ];
  networking.nameservers = [ "127.0.0.1" ];
  networking.enableIPv6 = false;

  time.timeZone = "America/Chicago";
  i18n.defaultLocale = "en_US.UTF-8";
  console = {
    font = "Lat2-Terminus16";
    keyMap = "us";
  };

  systemd.tmpfiles.rules = [
    "L+ /usr/local/bin - - - - /run/current-system/sw/bin/"
  ];

  virtualisation.docker = {
    enable = true;
    storageDriver = "btrfs";
    logDriver = "json-file";
    daemon.settings.features.cdi = true;
    rootless.daemon.settings.features.cdi = true;
  };

  users.users.jade = {
    isNormalUser = true;
    shell = pkgs.zsh;
    extraGroups = [
      "wheel"
      "docker"
    ];
    packages = with pkgs; [
      tree
    ];
    hashedPassword = "$6$sDfLSHBDw34Mi75P$VZSvinODReSBLOAzjMqdjnY9bftEs1AwOOzZioZ4Pco86hGOFE.UKzrmAopU4zS6w.5Env15XgB5Lds1DqRjc0";
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDzIbh1w5EeOjFTWaQ9V5PFHf5ipVNQ33sjzpsNDNgfD jade@Jades-MacBook-Pro.local"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPlvznoql2lTnV8qHUE6G35OKEHYKuODHIsfILpo4L98 Generated By Termius"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFmO691Ujio3I1tNUGEnSnyhjl0vLCBNi3Q/u0P+UvEX joejad@joejadserver"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN6MCnmxn47X/aP9pQxNmHc2I6kkZqh5R+J4KdcJUhZI jade@mini"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOciDf2c/QVPKjPVgSXYg7LSg8nwL4J7JDf8mYO4cs11 iPad"
    ];
  };

  security.sudo.wheelNeedsPassword = false;
  programs.zsh.enable = true;

  environment.systemPackages = with pkgs; [
    R
    age
    basedpyright
    bash
    bind
    cargo
    cifs-utils
    ethtool
    fluxcd
    fzf
    gcc
    git
    gnumake
    helm
    kubectl
    lazygit
    lemminx
    lua
    lua-language-server
    luajitPackages.luarocks-nix
    neovim
    networkd-dispatcher
    nfs-utils
    nil
    nixfmt
    nodejs
    opencode
    postgresql_18
    ripgrep
    ruff
    rustup
    samba
    sops
    starship
    stow
    stylua
    tmux
    tree-sitter-cli
    vscode-json-languageserver
    yaml-language-server
    zoxide
    zsh
  ];

  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = false;
      PermitRootLogin = "no";
    };
  };

  networking.firewall.enable = false;
  system.stateVersion = "25.11";

  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver
    ];
    # nvidia-container-toolkit.enable = true;
    # nvidia = {
    #   modesetting.enable = true;
    #   powerManagement.enable = true;
    #   open = true;
    # };
  };

  services.unbound = {
    enable = true;
    settings = {
      server = {
        interface = [ "0.0.0.0" ];
        do-ip6 = false;
        access-control = [
          "127.0.0.1/32 allow"
          "10.47.59.0/24 allow"
        ];
        private-domain = [ "joejad.lan" ];
        domain-insecure = [ "joejad.lan" ];
        local-zone = "\"joejad.com.\" redirect";
        local-data = [
          "\"joejad.com. IN A 127.0.0.1\""
        ];
        module-config = "'respip validator iterator'";
      };
      forward-zone = [
        {
          name = "joejad.lan.";
          forward-addr = [
            "10.47.59.1"
          ];
        }
        {
          name = ".";
          forward-tls-upstream = "yes";
          forward-addr = [
            "1.1.1.1@853#cloudflare-dns.com"
            "8.8.8.8@853#dns.google.com"
          ];
        }
      ];
      rpz = [
        {
          name = "hageziPro";
          url = "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/rpz/pro.txt";
        }
      ];
    };
  };

  security.acme = {
    acceptTerms = true;
    defaults.email = "joejadjavajim@icloud.com";
    certs = {
      "joejad.com" = {
        dnsProvider = "cloudflare";
        dnsPropagationCheck = true;
        environmentFile = config.sops.secrets.acme_cloudflare_env.path;
        group = "nginx";
        domain = "*.joejad.com";
        extraDomainNames = [ "joejad.com" ];
        dnsResolver = "1.1.1.1:53";
      };
    };
  };

  services.nginx = {
    enable = true;
    recommendedGzipSettings = true;
    recommendedOptimisation = true;
    recommendedProxySettings = true;
    recommendedTlsSettings = true;
  };

}
