forgejo-mailer-password: ENC[AES256_GCM,data:YF//WIdLsBZc8zChHas6e9CZoA==,iv:dOiGLQ7D6ESWaLfxVpqgKaARS5V5DiPAN1Ob4PbOkHI=,tag:3ReuSTSXnRx1sDTpBZuOjA==,type:str]
forgejo-mailer-user: ENC[AES256_GCM,data:A9doxG+fEct1WaZoog/ES9st7Q5z07A=,iv:O0Tx98iZnDGM8t9nXTywAzwnMr2/uw0Owe0aMySf2Mo=,tag:TvxglL04H8V+efO1jdrCwQ==,type:str]
forgejo-mailer-from: ENC[AES256_GCM,data:9NGJPuMyg2iVYUDq67LMPhUEf6qzsac=,iv:x0+cC82apeXy+0Db+pSJ8PH5NG7U03OsH9BJRLKQwn8=,tag:r8WgPt482NCm/Ah/cdj3YQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVUdjaXFPcG5ZYjV0a1JG
            ZXlac2FQdlRzcnBodXZxejRPN2pXUkd0YmhFCmhQTTNWcDR0dGRHTFNzMUE5MDNm
            UEJLSlN3cXplVkdTUzJ3M2QrVFl5Wm8KLS0tIHFpY0QyeURXUGlpM3Nhc2FSUlpD
            SW5sVXNzZ2xoZlgvY2ZxbVdPbkFDYkUKycAbroJDCYyJxMrrhYrNygRrylQHNVjQ
            7mEo/tc4TIpyI8X3QXCXEzyAuUoGAGBhAttee5Bm1NhQrOB5zhWHDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17lrgxpene4hfzh8zz0vezmwdagtekvlmnfl3mvuf9nrjwzmjhcdqvtfg0e
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RzUrSi9uNG5LVWNnYkRK
            SzBWYkN3T0dzekF4ekZpdk4zT2lpU05iU1dNCkxDd05zWnJqcGJtTEx1d2pCdHRQ
            K0RWTVdDUkJoME5yc25WNi90QmZEZ1EKLS0tIFZsaElCa2xmblVoN1FJN3Q2TWdt
            eTU4YktaYnE4bkZub2h0aGZuR2pPdTgKQQdiiR/nNStJzXc003lkBdveRZHx7AQ3
            xEzXAA6SjaZVsTf7MUqItLPo1jyi5lbKOieRmec2DOxedBOZWtlkQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pe2tlqj0lgfdjfrv2ztcgaltgnyt82wdx4dwcgwt85q52l4ujpkq8qcycv
    lastmodified: "2026-05-30T15:46:31Z"
    mac: ENC[AES256_GCM,data:zuy5E6YpIwt14zupe44Nf4rBvCJISKQuoREgWL2utYy9mFUROE+CzeEyG2Gxq808kgD1NVNDLw/1tlcASpkzca2X7vJwWJ/D6imMCHw3WO+bDHgqwT1gVHBVJst0pEZX/GwhSjQbs8Dz4HdB3LfPcV0PG+uj+PzJfKaJwTWGJBQ=,iv:Iy/h/qUR2M2NcWV/OzoplgJRwUbj62Q6i0s3QwjKhKg=,tag:ClBc54aOf2z8OfvrhXcB+g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
