borgbackup_passphrase: ENC[AES256_GCM,data:n2BJZHyHtHtn3STPNt4+z6rti3pPRgShuw==,iv:o+07i95xUTvfPAuD02r/mspWWpb6rVsXDr347FE70o0=,tag:SOvuLU8jIZI2WN4srN0ybA==,type:str]
sops:
    age:
        - recipient: age17lrgxpene4hfzh8zz0vezmwdagtekvlmnfl3mvuf9nrjwzmjhcdqvtfg0e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVzN0S2RFazdaeTVHMEY4
            eUFVYTZ5VjRwQXhMYi9WK1ZEUk5DNVJEQzJRCmJBWGcrcklVLzFwNS9GSkZ5ZW9W
            SDRxdk95cmwxZkViNWEwbHpRditPblkKLS0tIDZDNzk0T1V3UUNRY2NlYVVtS04r
            c09rMVRBK1lGWHRkaTBPWnFGUjNmNEkKlKh3oV4+eFe1kVyfmMxrdy6niNwn6jAs
            +PYqCVy76taTf/Ng56cOMxyd74OpoRlZUMrZyg6OxgygRHVl6OqDcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T22:48:44Z"
    mac: ENC[AES256_GCM,data:FZ+UDivsjJH0grnBWxEx36FrAfIxg4VtrGBp+jPmW8eTTmhM/QE1v/nki+x0G70AUnuub0M+sp2yEYmUlZ4OtoMno1wSRSYykDIzr6FsQaVaLcWr0hF1f26TPkoi7AirgzW8JkKdIWamcEOce63xq+9S0CgSekYB852I4nhNv9Q=,iv:XkfOB0a5xMwtoRq1sXlheRepu31owgDVU0vIusL7ppU=,tag:lmW6howFZSw3uxpURCmc+A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
