borgbackup_passphrase: ENC[AES256_GCM,data:n2BJZHyHtHtn3STPNt4+z6rti3pPRgShuw==,iv:o+07i95xUTvfPAuD02r/mspWWpb6rVsXDr347FE70o0=,tag:SOvuLU8jIZI2WN4srN0ybA==,type:str]
vaultwarden_env: ENC[AES256_GCM,data:TVDzSLNcRg6NjFGkubhkx04jIutjTD3+6JvKM9dEi36Uh0c8FM8ovUmOxkJbPRg4Bys4AKQ7RosiWv7VEThtRoS3yNh38uhKW7f89kTu5NnBfNxTNy5VvmkrB+nLtqxLpVMzcNL/k9u1K53JmRzZCPmlquGf4cYOY11B6TFm9PyJHgv/SKNF4x22I8mWWOoR6RmEkMJ7PpOc1gGqoaWVD3Tik8xQBxjYw9zfE2ztBZuwpkSyid5kW+C1bSEkiTP4vPY+u6g4H3p58nRgAXoa+i5RcaEmNKVTIxC1A4+9C4ySsOKF/p8sCJkyp6Z9XA7ykzcw2aTpihvH04aG6srmp/hAzuX2lRXs/w8wr2M/fNRN4eZYEXwJE4yMKse2igUcOsP2W4WClcqHxFekEnO1+0/oSRS2RWltxAGypZPPFm2cKrbYYOI1A42ZfmqRLUXR1ungd9up+RYD557XS/PxW4/dE5fkIgZfQbvXqt3tCrRE9U3a0ZHcABPV+rnVaPw=,iv:6UMZbWSjFfP2gv27nXH0vqOYKRMyp0qrZs3q528N7ng=,tag:t0xYHShLy/+CJtkBLiBIvg==,type:str]
sops:
    age:
        - recipient: age17lrgxpene4hfzh8zz0vezmwdagtekvlmnfl3mvuf9nrjwzmjhcdqvtfg0e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVzN0S2RFazdaeTVHMEY4
            eUFVYTZ5VjRwQXhMYi9WK1ZEUk5DNVJEQzJRCmJBWGcrcklVLzFwNS9GSkZ5ZW9W
            SDRxdk95cmwxZkViNWEwbHpRditPblkKLS0tIDZDNzk0T1V3UUNRY2NlYVVtS04r
            c09rMVRBK1lGWHRkaTBPWnFGUjNmNEkKlKh3oV4+eFe1kVyfmMxrdy6niNwn6jAs
            +PYqCVy76taTf/Ng56cOMxyd74OpoRlZUMrZyg6OxgygRHVl6OqDcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T15:27:52Z"
    mac: ENC[AES256_GCM,data:hG9jaqcUp1chzMJZHzg00dauaZMSX+dPBM/XHKY1KyYUehsMEiAfTRAWmst3tdOHvr3OTzfDW9VIgSwJE2tPyIRAFR5HNSep+toXr3pLmAFfPAMnSClQfJdvgqJ1yOx3bUpO0An7QKEfRuE8x+WjFMsmvo67kc3SDe/7+bBoIlU=,iv:VzGPgwQklosSF5yl96jfNpexaF6UkDORL4SLl9rz6jc=,tag:Eq3l4G89UZAp5gdeJmdACg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
